
version: 2

# Define variables that can be overridden in Bamboo
variables:
  - &dotnet-version 8.0
  - &nuget-feed: ${bamboo.nuget.feed}
  - &nuget-username: ${bamboo.nuget.username}
  - &nuget-password: ${bamboo.nuget.password}
  - &build-configuration: Release
  - &test-runner: trx
  - &test-results: test-results.trx

plan:
  project-key: DOTNET
  key: BUILD
  name: .NET Project Build

stages:
  - Build:
      jobs:
        - Build Job

Build Job:
  tasks:
    - checkout:
        repository: default
        path: .
        force-clean-build: true
    
    # Configure NuGet credentials if private feed is used
    - script:
        interpreter: SHELL
        scripts:
          - |
            if [ -n "${bamboo.nuget.feed}" ]; then
              dotnet nuget add source ${bamboo.nuget.feed} \
                --name private-feed \
                --username ${bamboo.nuget.username} \
                --password ${bamboo.nuget.password} \
                --store-password-in-clear-text
            fi
    
    # Build and test
    - script:
        interpreter: SHELL
        scripts:
          - dotnet restore --interactive
          - dotnet build --configuration ${bamboo.build.configuration} --no-restore
          - dotnet test --configuration ${bamboo.build.configuration} --no-build --no-restore --logger "${bamboo.test.runner};LogFileName=${bamboo.test.results}"
    
    # Publish artifacts
    - script:
        interpreter: SHELL
        scripts:
          - dotnet publish --configuration ${bamboo.build.configuration} --output ./publish
    
    # Publish test results
    - test-parser:
        type: ${bamboo.test.runner}
        directory: "**/TestResults"
        result-mask: "*.trx"
    
    # Create build artifacts
    - artifact:
        name: Build Output
        location: ./publish
        pattern: "**/*"
        shared: true
        required: true

requirements:
  - os: windows
  - dotnet: ${bamboo.dotnet.version}

# Environment variables available to all jobs
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_NOLOGO: true
  NUGET_XMLDOC_MODE: skip

triggers:
  - repository-polling:
      cron: "0 0/15 * * * ?"  # Check every 15 minutes

notifications:
  - email:
      recipients: ${bamboo.notification.email}
      on:
        - failed
        - error
        - success

# Artifact sharing between builds
artifact-definitions:
  - name: Build Output
    location: ./publish
    pattern: "**/*"
    shared: true
    required: true
