version: 2
plan:
  name: Aspire Windows Service CI
  key: ASPIREWINCI
  project: ASPIRE

stages:
  - Build
  - Test
  - Package

triggers:
  - polling:
      interval: 300

variables:
  solution.name: MyAspireApp.sln
  apphost.project: src/MyAspireApp.AppHost
  output.path: artifacts

source-repository:
  type: git
  url: https://github.com/your-repo.git
  branch: main

tasks:
  - stage: Build
    jobs:
      - name: Build Solution
        tasks:
          - script:
              name: Restore and Build
              script: |
                dotnet restore $solution.name
                dotnet build $solution.name -c Release --no-restore

  - stage: Test
    jobs:
      - name: Run Tests
        tasks:
          - script:
              name: Execute tests
              script: dotnet test $solution.name -c Release --no-build

  - stage: Package
    jobs:
      - name: Package Services
        tasks:
          - script:
            interpreter: BINSH_OR_CMDEXE
            file: scripts/generate_manifest
            working-dir: rgService
            description: Generate Aspire Manifest

          - script:
            interpreter: BINSH_OR_CMDEXE
            file: scripts/publish_and_package
            working-dir: rgService
            description: Publish and Package Projects


          - artifacts:
              name: Save Artifacts
              location: $output.path
              pattern: "*.zip"
              shared: true